# Generated by Django 2.1.3 on 2018-12-30 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_comment_text', models.TextField(max_length=400)),
                ('created_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('latest_change_time_stamp', models.DateTimeField(null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_comment_text', models.TextField(max_length=400)),
                ('created_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('latest_change_time_stamp', models.DateTimeField(null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('main_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentcomment.MainComment')),
            ],
        ),
    ]
