# Generated by Django 2.1.3 on 2019-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentcomment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincomment',
            options={'permissions': (('change_comment', 'Can change the comment'), ('look_up_all', 'Can look up all comments'))},
        ),
        migrations.AlterModelOptions(
            name='othercomments',
            options={'permissions': (('change_comment', 'Can change the comment'), ('look_up_all', 'Can look up all comments'))},
        ),
        migrations.RemoveField(
            model_name='othercomments',
            name='main_comment',
        ),
        migrations.AddField(
            model_name='othercomments',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maincomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maincomment',
            name='latest_change_time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='othercomments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='othercomments',
            name='latest_change_time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
